FROM adoptopenjdk:15
EXPOSE 8080
ENV MINIO_ENDPOINT=""
ENV MINIO_ACCESS=""
ENV MINIO_SECRET=""
ENV TSTUDIO_SERVICE_GITHUB=""
ENV TSTUDIO_SERVICE_GITLAB=""
ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","/app.jar"]

